//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string Category { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Author { get; set; }
        public string Image_src { get; set; }
        public double ISBN { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
