//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Shopping_cart = new HashSet<Shopping_cart>();
        }
    
        public string Category { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public System.DateTime Date { get; set; }
        public string Author { get; set; }
        public string Image_src { get; set; }
        public double ISBN { get; set; }
        public decimal Price { get; set; }
        public int Rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shopping_cart> Shopping_cart { get; set; }
    }
}
