//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditcard_details
    {
        public string CC_number { get; set; }
        public string Owner_name { get; set; }
        public string Expiry_date { get; set; }
        public string CVV { get; set; }
        public int User_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
