//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public Nullable<int> OrderDetails_id { get; set; }
        public string Order_status { get; set; }
        public Nullable<int> Payment_id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> User_id { get; set; }
        public int Order_Number { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual User User { get; set; }
    }
}
